databases: 
  - name: postgres
      
services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh" 
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatavase:
          name: postgres
          property: connectionString
              